env:
  global:
    - secure: BVTdzR/ApepZ4VZ8VIwUpyIr1NpnpcTh4Tb2jgqBB8EWnQVpA1i8tWwSUI5Oj2rgmcI97qDWQXGHxXOjC9/0SiMNsl1QoTtXs1bFG2SvJtmWrCAfR91MLB0yAwvZCA0opLuCtItHoAfwmSQrjW8s+nnCVNYdUw1J1HyR7/84/jlD2CGwGNMvhzZJ1Xl3vacVBOpQt+DDnAAz8419cUJPn4hD3dr3otpBfGWHO49RAqoryEbiQdmgR/hS0YCpWSy0yOQS5dzsqZR+bwE64TdNb/PdVslJRq1u+Y64e1owrAGAbCWx/nEB4qsmpvrZMQhvK1IJ4nLlNWukOqP+Z22g+e3FcuZtDwRDTyePjEitUjJM3tDFGtRPwg6juLGDsiC98mUpJiC0ToJCsIPaVWxaC4Mmnt0T01hex2Vdv4rmY+f8dyC5GEJWHtE3ucZOqlLRYUIKjkYfPm+pnJLl2TTZ+x7GCbbg0m9q/vne/Jn1KGu7HbjIrrZeGwWDX8sy6cLeojIql5uodA5O7VFwmOMnUPL66EyulQ1Herc7ojejozmUq23DB7an+FRYnA0IXqRDOpPUQMc0Qb2GbNpqQgSDMDBl/+LC7do82XNj5zbPUky2dwqjG6FiJx4mjov7Xved9UDxviz1kXisuqd6dMk+r86mvFiM5GrLzIeWOTU7/nU=
    - secure: lFIbmsG0Nx+lAziSpqQK5cIZ1e8WDDrgaWJVgtlWsQKGi2abmRaoiuF7bzvxOa2fP+L9fw/VERUSj1w0CcS6zFsWdZ2F7tuUJZ3+O56hSPaO21OmwpoxhjK8BNmCwPu7Cqdq0kl4Vdv0H2EVRAeqzPeakowaJx3ARjbGIa0NI3EnzwplKzbh9scTXewes39TACb6l95lZt647eBbuaSIWHSH51MzlNIZQzErTBZ58nLqvuhlEpI5sSkoDeyXaGoRZ7yP0OBWP0Kp4s0sm163Xo4QkmrzRxiD9NXO9UkGDfkpDwYXKF4CZqW1tS4xl74Dy1hvgxzxLAGz4krprEMqyyTsqqy2LTXzzbq8+nnkuwOOFsYEZDU6/jigZltb/ZjUXf5p4XgvX/BdEk5R5XetKFMZCpxWVFzY3Ym/KUJT+6ttQ0s898s7/URcC83aVhrdPaJUT+47Q4xzGaWss7OZjDn6Pu0ajtT2u6PEDdBtMTcBZNhWL+Hiqti2o2tqGCuKNBI7t4UC2RA41IWCMgXMdpY06UeGb5OTiz/6mP3vhIMKwS8g24SXedy+gpnOtIM7R3VWZ7MMlf36n6qVeLamIWll1Na3RuAX3jCYnw0Pfj77aZUuEd8+Xo/2q9hxqrgrreoqTSnvd0wsjRxuYd8wJM2aW4cCWffVVZwlJHeGLY0=
    - secure: Hyq3DFwmeNVxjM821zARVrbBQ2Wr3W9/4B3c/cRuwHnc3iOee8BJBJpOHK9FICjT3bVVWqTJW5uwzD9JZXgN943lwut6X50ebsi/p3eL2Tt7ZH/aADOr2I9pyOnqDRkoSyBbgaEzps98uDfgKx5uW3md4N7L63KqXSeMOsmv8aT31Fky9olEnysd0Bx5+8KRmT46D4wdfuNfP4I469Kxx2Cofto//EtMYEs6GJLUTCGpGpQ5amf2/GkZeFCS2Zii60R35woAGp5bd8ehjFEt4uRax9AsfNbLb2SA6SYRjpd6bAmKbBPL2BmCyN1npfB+JRgx8oPRbcU/smYPG5SiidQz4eJp0DfaCmPoz62oHDgwlaqBLyNVA0R2ApbtyfzeB6WMona7qsXDv79MDwqhJcAM52iJ6U7SDFu5nZ8PXMQIYfL+8U59sANDTns9Gz0StgwQvjUG+9ZW6CMMy4DKL4H2LEEMTsKBk8Mxi5HjNUfyrFbbYsDMxaRDDbUCz6EIlkHQa71ayf1EtWE5ajZs+CjQ1vNtlpszbkdSrhQlm/420DwwJZ+A/7FbGH6kg0ie9JiA+RsvUk7SUruDcsyawk2LVIB74wILHwoVW+1IPTejtv02mMk4OM5N3RmpBSyHeoH+2a3jaQZSp0zhuw5sDdWU1a2zcqyR1rEpfeEmetM=
    - COMMIT=${TRAVIS_COMMIT::8}
sudo: required
group: edge
install:
  - docker pull alpine

before_script:
  - docker build -t build_static build_static
  - ./build_webapp.sh

script:
  - docker build -t minecraft .
  - docker images

after_success:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag tmaurice/dnsbin:$COMMIT tmaurice/minecraft:latest
  - docker push tmaurice/minecraft:$COMMIT
  - docker push tmaurice/minecraft:latest

